# Service Vote 

apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: 5000 # App roda na Porta 5000 que iremos acessar
    targetPort: 80
    nodePort: 31000
  selector:
    app: vote  